# Generated by Django 5.1 on 2024-08-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="plaid_item_id",
            new_name="auth_token_id",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="account_subtype",
            new_name="connection_type",
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="plaid_account_id",
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trn_date", models.DateTimeField()),
                ("trn_type", models.CharField(max_length=50)),
                ("trn_description", models.TextField()),
                ("trn_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial.account",
                    ),
                ),
            ],
        ),
    ]
